//var input1,input2,input3;

function setup() {
  //createCanvas(900,800);
 /* input1=createInput();
  input1.position(130,170);
  input2=createInput();
  input2.position(210,210);
  input3=createInput();
  input3.position(130,250);
  */
}

function draw() {
  background(255);
/*
<HTML>
<BODY>
<FORM>
<CENTER><H1>LIBRARY INFORMATION</H1></CENTER>
NAME:<INPUT TYPE=TEXT><P>
ADMISSION NO.:<INPUT TYPE=TEXT><P>
HOW OFTEN YOU BORROW A BOOK FROM THE LIBRARY ?:<P>
<INPUT TYPE=RADIO NAME=R1>ONCE A WEEK
<INPUT TYPE=RADIO NAME=R1>TWICE A WEEK
<INPUT TYPE=RADIO NAME=R1>NEVER <P>
WHAT KIND OF BOOKS DO YOU READ?
<INPUT TYPE=CHECKBOX=C1>MYSTERIES
<INPUT TYPE=CHECKBOX=C2>TRAVELOGUES
<INPUT TYPE=CHECKBOX=C3>BIOGRAPHIES<P>
FAVOURITE BOOK:<INPUT TYPE=TEXT><P>
FAVOURITE AUTHOR:<INPUT TYPE=TEXT><P>
<INPUT TYPE=RESET VALUE=REDO>
<INPUT TYPE=SUBMIT VALUE=SUBMIT>
</FORM>
</BODY>
</HTML>
*/
}